sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - docker

addons:
  sonarcloud:
    organization: "piotrzlotowski-github"
script:
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
