language: java
sudo: required
jdk:
- oraclejdk9
services:
- docker
addons:
    sonarcloud:
        organization: piotrzlotowski-github
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
