sudo: required

language: java
jdk:
  - oraclejdk8
services:
  - docker

addons:
  sonarcloud:
    organization: "piotrzlotowski-github"
    token:
      secure: "9ba0d57761d38a2a748c46ada3efd37b9fba65b4"
jdk:
  - oraclejdk8
 script:
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
    directories:
      - '$HOME/.m2/repository'
      - '$HOME/.sonar/cache'